export const enum EModalVariables {
  RATING_MODAL = "RATING_MODAL",
  SEARCH_CHATS_MODAL = "SEARCH_CHATS_MODAL",
  TELEGRAM_AUTH_MODAL = "TELEGRAM_AUTH_MODAL",
  TELEGRAM_CONTACTS_MODAL = "TELEGRAM_CONTACTS_MODAL",
  TODOIST_AUTH_MODAL = "TODOIST_AUTH_MODAL",
  TODOIST_CREATE_TASK_MODAL = "TODOIST_CREATE_TASK_MODAL",
}
