version: "3.8"

services:
  ollama:
    build:
      context: .
      dockerfile: model/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - CUDA_VISIBLE_DEVICES=""
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices: []
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mock-ml-service:
    build: ./mock/ml
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-llama3.2:3b}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-0}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
      - TELEGRAM_DATA_DIR=/app/data
    volumes:
      - telegram_data:/app/data
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  seed-data:
    build: ./mock/database
    container_name: seed-data
    environment:
      - PYTHONUNBUFFERED=1
      # Всегда используем автоматический режим
      - AUTO_START=true
      # Дата начала периода
      - START_DATE=2025-01-01
      # Дата окончания периода
      - END_DATE=2025-12-31
      # Логин тестового пользователя
      - SEED_USER_LOGIN=test_user_3@mail.ru
      # Пароль тестового пользователя
      - SEED_USER_PASSWORD=test_password_123
    restart: "no"

volumes:
  ollama:
  telegram_data:
