version: '3.8'

services:
  # Nginx Proxy Manager
  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: nginx-proxy-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-proxy-db
    networks:
      - proxy-network

  # Database for Nginx Proxy Manager
  nginx-proxy-db:
    image: jc21/mariadb-aria:latest
    container_name: nginx-proxy-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - proxy-network

  mock-ml-service:
    build: ./mock/ml_for_test_deploy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - app
    restart: always

  app:
    build:
      context: ./back
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      # Передаем переменную окружения для AssemblyAI API
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-}
      - MODEL=http://mock-ml-service:8000
    depends_on:
      - postgres
      - minio
      # - recognizer-service
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./back/internal/database/migrations
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
      MINIO_UPDATE: "off"
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }    # check if Minio is alive
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid                # start Minio in the background
        while ! isAlive; do sleep 0.1; done                                # wait until Minio is alive
        mc alias set minio http://127.0.0.1:9000 minio-user minio-password # setup Minio client
        mc mb minio/voices || true                                         # create a test bucket
        mc mb minio/files || true                                          # create additional bucket
        mc anonymous set public minio/voices                               # make the test bucket public
        mc anonymous set public minio/files                                # make the additional bucket public
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid            # stop Minio
        while isAlive; do sleep 0.1; done                                  # wait until Minio is stopped
        exec minio $$0 "$$@"                                               # start Minio in the foreground
      '
    command: server /data --json --console-address ':9090'
    ports:
      - "9000:9000/tcp"
      - "9090:9090/tcp" # open http://127.0.0.1:9090 (9000 is the API port)
    volumes:
      - minio-data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      start_period: 10s
    security_opt: [no-new-privileges:true]

volumes:
  ollama:
  postgres_data:
  minio-data: {}

networks:
  proxy-network:
    driver: bridge