services:
  ml:
    build:
      context: ./ml
      dockerfile: deploy/Dockerfile
    env_file:
      - ./.env
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy-network

  ollama:
    build:
      context: .
      dockerfile: model/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - proxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8080}
    ports:
      - "5173:80"
    depends_on:
      - app
    restart: always
    networks:
      - proxy-network

  app:
    build:
      context: ./back
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-}
      - MODEL=http://ml:8000
      - FRONT_ORIGIN=http://localhost:5173
      - DATABASE_URL=postgres://app:app123@postgres:5432/app
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio-user
      - MINIO_SECRET_KEY=minio-password
      - MINIO_USE_SSL=false
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      ml:
        condition: service_healthy
    restart: always
    networks:
      - proxy-network

  integrations:
    build: ./integration
    ports:
      - "4444:4444"
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-0}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}
      - TELEGRAM_DATA_DIR=/app/data
      - API_BASE_URL=http://app:8080
    volumes:
      - telegram_data:/app/data
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy-network

  migrations:
    build:
      context: ./back/internal/database/migrations
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://app:app123@postgres:5432/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - proxy-network

  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
      MINIO_UPDATE: "off"
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }
        minio $$0 "$$@" --quiet & echo $$! > /tmp/minio.pid
        while ! isAlive; do sleep 0.1; done
        mc alias set minio http://127.0.0.1:9000 minio-user minio-password
        mc mb minio/voices || true
        mc mb minio/files || true
        mc anonymous set public minio/voices
        mc anonymous set public minio/files
        kill -s INT $$(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $$0 "$$@"
      '
    command: server /data --json --console-address ':9090'
    volumes:
      - minio-data:/data:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      start_period: 10s
    security_opt: [no-new-privileges:true]
    networks:
      - proxy-network

volumes:
  ollama:
  postgres_data:
  minio-data: {}
  telegram_data:

networks:
  proxy-network:
    driver: bridge
    name: proxy-network