"""
This type stub file was generated by pyright.
"""

from typing import Any
from ml.agent.graph.state import GraphState

"""Tool execution node for research workflow."""
def research_tool_call_node(state: GraphState, client: Any) -> GraphState:
    ...

