"""
This type stub file was generated by pyright.
"""

from ml.agent.graph.state import GraphState
from ml.api.ollama_calls import ReasoningModelClient

"""Observation processing node for the research workflow."""
MAX_RESEARCH_ITERATIONS = ...
def research_observer_node(state: GraphState, client: ReasoningModelClient) -> GraphState:
    ...

