"""
This type stub file was generated by pyright.
"""

from ml.agent.graph.state import GraphState
from ml.api.ollama_calls import ReasoningModelClient

def thinking_planner_node(state: GraphState, client: ReasoningModelClient) -> GraphState:
    ...

