"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator
from langgraph.graph import StateGraph
from ml.api.ollama_calls import ReasoningModelClient
from ml.configs.message import RequestPayload, Tag
from ollama import ChatResponse

logger = ...
def create_pipeline(client: ReasoningModelClient) -> StateGraph:
    """Create the LangGraph pipeline."""
    ...

def run_pipeline(payload: RequestPayload) -> tuple[Iterator[ChatResponse], Tag]:
    ...

