"""
This type stub file was generated by pyright.
"""

from fastapi import FastAPI

logger = ...
async def lifespan(app: FastAPI): # -> Generator[None, Any, None]:
    ...

def create_app() -> FastAPI:
    """Configure and return the FastAPI application."""
    ...

