"""
This type stub file was generated by pyright.
"""

from typing import Iterator, List, TypeVar
from ollama import ChatResponse
from pydantic import BaseModel
from ml.configs.model_config import EmbeddingClientSettings, ReasoningClientSettings
from ml.configs.message import ChatHistory

T = TypeVar("T", bound=BaseModel)
logger = ...
class ReasoningModelClient:
    def __init__(self, settings: ReasoningClientSettings = ...) -> None:
        ...
    
    def call(self, messages: ChatHistory, **kwargs) -> str:
        ...
    
    def stream(self, messages: ChatHistory, **kwargs) -> Iterator[ChatResponse]:
        ...
    
    def call_structured(self, messages: ChatHistory, output_schema: type[T], **kwargs) -> T:
        ...
    


class EmbeddingModelClient:
    def __init__(self, settings: EmbeddingClientSettings = ...) -> None:
        ...
    
    def call(self, content: str, **kwargs) -> List[float]:
        ...
    


