"""
This type stub file was generated by pyright.
"""

import logging
from ml.api.types import ModelClients

logger: logging.Logger = ...
_MODEL_ENV_VARS: list[str] = ...
async def get_models_from_env() -> list[str]:
    """Read .env to get the configured model identifiers."""
    ...

async def download_missing_models(available_models: list[str], requested_models: list[str]) -> None:
    ...

async def init_models() -> ModelClients:
    ...

async def fetch_available_models() -> list[str]:
    ...

async def fetch_running_models() -> list[str]:
    ...

async def warmup_models(clients: ModelClients) -> None:
    ...

