"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Literal, Union
from ml.api.ollama_calls import EmbeddingModelClient, ReasoningModelClient

logger = ...
_MODEL_ENV_VARS = ...
async def get_models_from_env() -> List[str]:
    """Read .env to get the configured model identifiers."""
    ...

async def download_missing_models(available_models: List[str], requested_models: List[str]) -> None:
    ...

async def init_models() -> Dict[str, Union[ReasoningModelClient, EmbeddingModelClient]]:
    ...

async def fetch_available_models() -> List[str]:
    ...

async def fetch_running_models() -> List[str]:
    ...

async def warmup_models(clients: Dict[Literal["embeddings", "chat"], Union[ReasoningModelClient, EmbeddingModelClient]]) -> None:
    ...

