"""
This type stub file was generated by pyright.
"""

import logging
from collections.abc import Iterator
from typing import Any, TypeVar
from ollama import ChatResponse
from pydantic import BaseModel
from ml.configs.message import ChatHistory
from ml.configs.model_config import EmbeddingClientSettings, ReasoningClientSettings

T = TypeVar("T", bound=BaseModel)
logger: logging.Logger = ...
class ReasoningModelClient:
    def __init__(self, settings: ReasoningClientSettings | None = ...) -> None:
        ...
    
    def call(self, messages: ChatHistory, **kwargs: Any) -> str:
        ...
    
    def stream(self, messages: ChatHistory, **kwargs: Any) -> Iterator[ChatResponse]:
        ...
    
    def call_structured(self, messages: ChatHistory, output_schema: type[T], **kwargs: Any) -> T:
        ...
    


class EmbeddingModelClient:
    def __init__(self, settings: EmbeddingClientSettings | None = ...) -> None:
        ...
    
    def call(self, content: str, **kwargs: Any) -> list[float]:
        ...
    


