"""
This type stub file was generated by pyright.
"""

from typing import TypedDict
from ml.api.ollama_calls import EmbeddingModelClient, ReasoningModelClient

class ModelClients(TypedDict):
    chat: ReasoningModelClient
    embeddings: EmbeddingModelClient
    ...


