"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from ml.api.ollama_calls import ReasoningModelClient
from ml.configs.message import ChatHistory, Tag

logger = ...
class DefinedTag(BaseModel):
    tag: Tag
    ...


def define_tag(last_message: ChatHistory, reasoning_client: ReasoningModelClient) -> Tag:
    """Makes a structured output call to reasoning client"""
    ...

