"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel

class ToolResult(BaseModel):
    """Result from tool execution."""
    success: bool
    data: Any
    error: Optional[str] = ...


class BaseTool(ABC):
    """Base class for all tools."""
    @property
    @abstractmethod
    def name(self) -> str:
        """Tool name."""
        ...
    
    @property
    @abstractmethod
    def description(self) -> str:
        """Tool description."""
        ...
    
    @property
    @abstractmethod
    def schema(self) -> Dict[str, Any]:
        """JSON schema for tool arguments."""
        ...
    
    @abstractmethod
    def execute(self, **kwargs: Any) -> ToolResult:
        """
        Execute the tool with given arguments.
        
        Args:
            **kwargs: Tool arguments
            
        Returns:
            ToolResult with execution result
        """
        ...
    


