"""
This type stub file was generated by pyright.
"""

"""Utilities for fetching and processing web pages for search enrichment."""
USER_AGENT = ...
def fetch_page_html(url: str, timeout: float, max_bytes: int) -> str:
    """Download HTML content for ``url`` with size and timeout guards.

    Args:
        url: Target URL.
        timeout: Total request timeout in seconds.
        max_bytes: Maximum number of response bytes to read.

    Returns:
        Raw HTML as a string (truncated to ``max_bytes`` if necessary).

    Raises:
        RuntimeError: If the request fails for any reason.
    """
    ...

def html_to_text(html: str) -> str:
    """Convert HTML to a normalized plain-text representation."""
    ...

def build_excerpt(text: str, query: str, *, window: int) -> str:
    """Build a context window around the first query match in ``text``.

    Args:
        text: Source text to scan.
        query: Original search query.
        window: Number of characters to include on each side of the match.

    Returns:
        A trimmed excerpt containing the query terms, or the leading portion of
        ``text`` when no match is found.
    """
    ...

__all__ = ["fetch_page_html", "html_to_text", "build_excerpt"]
