"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from ml.agent.tools.base import BaseTool

_tool_registry: Dict[str, BaseTool] = ...
def get_tool_registry() -> Dict[str, BaseTool]:
    """Get the global tool registry."""
    ...

def register_tool(tool: BaseTool) -> None:
    """Register a tool in the global registry."""
    ...

def get_tool(name: str) -> Optional[BaseTool]:
    """Get a tool by name."""
    ...

def initialize_tools() -> None:
    """Initialize default tools."""
    ...

