"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
from ml.agent.tools.base import BaseTool, ToolResult

DEFAULT_FETCH_TIMEOUT = ...
DEFAULT_MAX_BYTES = ...
DEFAULT_EXCERPT_WINDOW = ...
DEFAULT_CONTENT_PREVIEW = ...
MAX_FETCH_WORKERS = ...
class WebSearchTool(BaseTool):
    """DuckDuckGo web search tool."""
    def __init__(self, max_results: int = ..., *, fetch_timeout: float = ..., max_bytes: int = ..., excerpt_window: int = ..., content_preview: int = ...) -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def description(self) -> str:
        ...
    
    @property
    def schema(self) -> Dict[str, Any]:
        ...
    
    def execute(self, query: str, **kwargs: Any) -> ToolResult:
        """
        Execute web search.
        
        Args:
            query: Search query string
            
        Returns:
            ToolResult with search results
        """
        ...
    


