"""
This type stub file was generated by pyright.
"""

from typing import Iterator
from ml.configs.message import RequestPayload, Tag
from ollama import ChatResponse

def workflow(payload: RequestPayload) -> tuple[Iterator[ChatResponse], Tag]:
    ...

def workflow_collected(payload: RequestPayload) -> tuple[str, Tag]:
    ...

