"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel, field_validator
from enum import Enum
from typing import Dict, List, Optional

class Role(str, Enum):
    system = ...
    user = ...
    assistant = ...


class Message(BaseModel):
    id: Optional[int] = ...
    role: Role
    content: str


class ChatHistory(BaseModel):
    messages: List[Message] = ...
    def add_or_change_system(self, content: str) -> None:
        ...
    
    def add_user(self, content: str) -> None:
        ...
    
    def add_assistant(self, content: str) -> None:
        ...
    
    def last_message_as_history(self) -> ChatHistory:
        ...
    
    def messages_list(self) -> List[Dict[str, str]]:
        ...
    
    def model_dump_string(self) -> str:
        ...
    


class ModelMode(str, Enum):
    Fast = ...
    Thiking = ...
    Research = ...
    Auto = ...


class Tag(str, Enum):
    General = ...
    Finance = ...
    Law = ...
    Marketing = ...
    Management = ...


class RequestPayload(BaseModel):
    messages: ChatHistory
    chat_id: str
    tag: Optional[Tag] = ...
    mode: ModelMode
    system: str
    file_url: str
    is_voice: bool
    @field_validator("messages", mode="before")
    @classmethod
    def normalize_messages(cls, message_list): # -> dict[str, Any]:
        ...
    
    @field_validator("tag", mode="before")
    @classmethod
    def replace_tag(cls, v): # -> None:
        ...
    


