"""
This type stub file was generated by pyright.
"""

from .fast_answer_prompt import get_fast_answer_prompt
from .research_observation_prompt import get_research_observation_prompt
from .research_reason_prompt import get_research_reason_prompt
from .research_tool_prompt import get_research_tool_prompt
from .tag_define_prompt import get_tag_define_prompt
from .voice_validation_prompt import VoiceValidationResponse, get_voice_validation_prompt

__all__ = ["get_voice_validation_prompt", "VoiceValidationResponse", "get_fast_answer_prompt", "get_research_reason_prompt", "get_research_tool_prompt", "get_research_observation_prompt", "get_tag_define_prompt"]
