"""
This type stub file was generated by pyright.
"""

from typing import Sequence
from ml.agent.graph.state import ResearchTurn
from ml.configs.message import ChatHistory

"""Prompt builder for synthesizing tool observations."""
def get_research_observation_prompt(conversation: ChatHistory, turn_history: Sequence[ResearchTurn], tool_name: str, documents: Sequence[str]) -> ChatHistory:
    """Build a prompt for interpreting tool outputs and updating the plan."""
    ...

