"""
This type stub file was generated by pyright.
"""

from typing import Optional, Sequence
from ml.agent.graph.state import ResearchTurn
from ml.configs.message import ChatHistory

"""Построитель подсказки для этапа рассуждений исследовательского агента."""
def get_research_reason_prompt(conversation: ChatHistory, turn_history: Sequence[ResearchTurn], latest_reasoning: Optional[str] = ...) -> ChatHistory:
    """Создать подсказку для рассуждений с учётом предыдущих ходов и черновика."""
    ...

