"""
This type stub file was generated by pyright.
"""

from typing import Optional, Sequence
from ml.agent.graph.state import ResearchToolRequest, ResearchTurn
from ml.configs.message import ChatHistory

"""Prompt builder for selecting and preparing a tool call."""
def get_research_tool_prompt(conversation: ChatHistory, turn_history: Sequence[ResearchTurn], pending_request: ResearchToolRequest, comparison_note: Optional[str] = ...) -> ChatHistory:
    """Build a prompt for validating and finalizing the next tool request."""
    ...

