"""
This type stub file was generated by pyright.
"""

from ml.configs.message import ChatHistory
from pydantic import BaseModel

class VoiceValidationResponse(BaseModel):
    voice_is_valid: bool
    ...


def get_voice_validation_prompt(message: ChatHistory) -> tuple[ChatHistory, type[VoiceValidationResponse]]:
    ...

